### ISSUE TITLE
App Compiling

### ISSUE THREAD

**Issue by alexbgameson** [SpigotPE-Team/SpigotPE-APP#2]
Hello. Can you please post on how to compile the app into an android apk?

**Comment by Asuna-Yuuki** [comment]
Uhh @alexbgameson use circleci

**Comment by alexbgameson** [comment]
How do I do that?

**Comment by Fabiansigala** [comment]
@alexbgameson don't worry we will compile it for you!

**Comment by alexbgameson** [comment]
Thank you so much!

**Comment by Fabiansigala** [comment]
When its ready i will post it on https://github.com/SpigotPE-Team/SpigotPE-APP/releases
